### ISSUE TITLE
Add Battery Energy and Power Draw from Motor to the Simulation

### ISSUE THREAD

**Issue by TheGreatFez** [TSoGiants/TSoG_X1#42]
One of the major factors that affect performance of an aircraft is the efficiency and total energy (battery size, fuel load) that the aircraft has.

Currently we have a fully updated Thrust Model but we need to update it with how much power the motor draws. Secondly, we need to add the battery capacity (in mAh). These together can give us the power consumption and overall flight time depending on how each Test Case is ran.

**Comment by adiojha629** [comment]
Thrust model was not using SimData structure. It does now!

**Comment by adiojha629** [comment]
The thrust model uses Throttle determine how efficient the motor is. I will update that value based on the battery state

**Comment by adiojha629** [comment]
I am assuming that we will use this battery [Battery Link](https://store.flitetest.com/tattu-3s-lipo-battery-45c-11.1v-1300mah-jstxh-tat-45c-1300-3s1p-xt60/p450620)

It's voltage can power the motors. Current Capacity is 1300mAh

**Comment by TheGreatFez** [comment]
> I am assuming that we will use this battery [Battery Link](https://store.flitetest.com/tattu-3s-lipo-battery-45c-11.1v-1300mah-jstxh-tat-45c-1300-3s1p-xt60/p450620)
> 
> It's voltage can power the motors. Current Capacity is 1300mAh

That looks pretty good, it's around the size of battery that is generally recommended.

**Comment by adiojha629** [comment]
My game plan:
Get electrical power drain by propeller from RPM and **Torque**

> Get Torque from Lift and Drag
> Get Lift and Drag from Aerodynamic Model

Get current drawn from power and voltage
> Current = Power / Voltage

To see when the battery is dead, I will multiple the current by one sec and illiterately subtract if from 1300 mAh
> If you have a variable current draw (I(t)) a good approximation for when the battery will die is:
> integral [ I(t) dt ] from 0 to t = 1300 mAh
> I will calculate each part of the integral by doing current * 1 sec (i(t) * dt)
>Then I subtract the value above from 1300 mAh

I still don't know how to relate the battery capacity remaining (1300 - value) to decrease the throttle.

**Comment by adiojha629** [comment]
I created a function call get_Prop_AOA(SimData) and also added a structure to sim data; SimData.Prop
Here's an overview of what is in the structure
>SimData.Prop.Diameter = 6; #inches
  SimData.Prop.Max_Volt = 11.1; #volts
  SimData.Prop.Kv = 2280; #RPM per volt
  SimData.Prop.RPM = @(Throttle) SimData.Prop.Max_Volt*SimData.Prop.Kv*Throttle;
  SimData.Prop.AoA = get_Prop_AOA(SimData)

These additions were made so that we can get the torque on the motor. ie, using the AOA we can use Trig and the values of drag and lift to estimate torque

**Comment by adiojha629** [comment]
Here's how I calculated AOA for the propeller. I solved for alpha in this [picture].(https://cdn.discordapp.com/attachments/722948706470461551/736299450376650844/unknown.png)

I know alpha is not exactly pitch because it only goes to the zero lift line, but I am assuming that it is close enough to the actual angle of attack.

alpha = theta - angle between V1 and V2.
theta = Pitch of the propellor (still need to figure out how to do this)
angle between V1 and V2 is arctan(v0/v2)
v0 = airspeed
v2 = linear speed of the propellor at the radius (diameter/4) **This is an assumption I am making**

Now I need to figure out the pitch of our propeller

**Comment by adiojha629** [comment]
New Game Plan:
Get Power from:
> P = F * v = Thrust * airspeed
Use power to get current. 
> Battery Capacity lost is = Current * dt
We store the current battery capacity (in mAh) in Results.battery_status.
The Thrust model now outputs both the thrust in x and y directions, and the amount of battery capacity lost.
In the main loop of TSoG_X1_Sim, this last value is subtracted from the current Results.battery_status.

**Comment by adiojha629** [comment]
Goal: Have the ThrustModel function only take inputs of SimData.
We need to augment SimData to record information on how much capacity is left in the battery
Variables Defined:
> SimData.battery_ratio %ratio between current battery capacity and full capacity (dimensionless)
> SimData.battery_update %change in battery capacity in mAh

In order to pass the value of battery_update to SimData, the output of Derivatives (kOut) has a term called battery update
> ie kOut.battery_update = ThrustModel(SimData)(3)
This kOut.battery_update is used in RK4 integration to update SimData.battery_update.

The Thrust model outputs 3 values:
> Thrust_x
>Thrust_y
>battery_update (in mAh)
